# Spring 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yvpao_backend?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  session:
    timeout: 86400
    store-type: redis
  data:
    redis:
      port: 6379
      host: localhost
      database: 0 # 建议写上


# 端口配置
server:
  port: 8080
  servlet:
    context-path: /api # 为所有请求加一个前缀

# Mybatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# springdoc-openapi项目配置
springdoc:
  swagger-zui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sonnet.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


