# Spring 配置
spring:
  datasource:
    url: jdbc:mysql://115.159.149.217:3306/yvpao_backend?serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 115.159.149.217
      port: 6379
      database: 0




